#' Load PSD-IV experimental data.
#'
#' Use this function to load data from the PSD-IV instrument. It is assumed that
#' the data is in the current working directory and has been generated by an 
#' Instrumentation Associates (IA) implementation. Data will be output on a per-
#' detector basis into the following directory structure:
#'   data\ExptMMMMM\ScanNN\SegOO\detPP.raw
#' 
#' @param numeric_range, vector of integers representing the experiments to pull into the data space
#' @param dets, vector of integers representing the detectors used; defaults to \emph{NA} to include all detectors
#' @param type, character string representing the return data type
#' 
#' @author Peter Norgard
#   version 0.1.0.1000
LoadPSDExperiment = function(numeric_range, dets=NA, type)
{
	# Construct directory names from numeric input values and call function to
	# read inside the directory
	dnames = sapply(1:length(numeric_range), function(i) sprintf("Expt%05d", numeric_range[i]));
	retval = lapply(1:length(dnames), function(i) read_ExperimentDirectory(dnames[i], dets, type));
	return(retval);
}